### ISSUE TITLE
Not working on instagram

### ISSUE THREAD

**Issue by modelfe** [qsniyg/maxurl#597] opened 2021-01-05 04:46 UTC
This doesn't seem to be working on instagram anymore. Here's two examples from https://www.instagram.com/elisha__h/

From stories: https://scontent-syd2-1.cdninstagram.com/v/t51.2885-15/sh0.08/e35/p640x640/135359174_1082901568802668_6910848405987390964_n.jpg?_nc_ht=scontent-syd2-1.cdninstagram.com&_nc_cat=1&_nc_ohc=pd1znUjk18EAX99lKQu&tp=1&oh=7051d46d2220ae191073643ee84c6570&oe=5FF67633

And from the timeline: https://scontent-syd2-1.cdninstagram.com/v/t51.2885-15/sh0.08/e35/s750x750/133895341_394130301809392_372065923939300795_n.jpg?_nc_ht=scontent-syd2-1.cdninstagram.com&_nc_cat=104&_nc_ohc=Vl8U2W-Bd8QAX86URVM&tp=1&oh=4ec6af8edc4beacd5c8d11c8d8050a4d&oe=601DDAD7

Neither are currently getting resized.

**Comment by qsniyg** [comment] 2021-01-05 04:52
Currently I'm unable to debug this on my side, and I'm not sure when I will be able to in the future (no account). Would you mind discussing this over [discord](https://discord.gg/fH9Pf54) or [matrix](https://matrix.to/#/#image-max-url:tedomum.net?via=tedomum.net)? Since a fair amount of back and forth might be required to fix this, it'll probably be easier to communicate over than github issues :)

If you can't/would rather not, let me know and we can do it over here too.

**Comment by modelfe** [comment] 2021-01-05 04:57
I just jumped on matrix now

**Comment by qsniyg** [comment] 2021-01-06 06:36
Closing as a duplicate of https://github.com/qsniyg/maxurl/issues/588

**Closed by qsniyg** 2021-01-06 06:36 UTC
Labels: bug, topic:rules
