### ISSUE TITLE
Blacklist rule not working

### ISSUE THREAD

**Issue by modelfe** [qsniyg/maxurl#639] opened 2021-02-05 04:48 UTC
I'm trying to exclude processing on twitter images, so I've added pbs.twimg.com to the blacklist in the rules section. However all pbs.twimg.com images are still being redirected. I've tried `pbs.twimg.com`, `pbs.twimg.com/*`, `pbs.twimg.com/**`, `pbs.twimg.com/media/*`, and `pbs.twimg.com/media/**`.

Additionally, it's not clear from the documentation how the URLs in the blacklist should be listed. Are they comma separated?

(And in case you're wondering, I've written my own rule using [Redirector](https://addons.mozilla.org/en-US/firefox/addon/redirector/) because I'd like for an image of the format:
https://pbs.twimg.com/media/Es3w7NrXIAIsf0v?format=jpg&name=900x900
to redirect to:
https://pbs.twimg.com/media/Es3w7NrXIAIsf0v.jpg:orig
rather than:
https://pbs.twimg.com/media/Es3w7NrXIAIsf0v?format=jpg&name=orig
because the latter naming format breaks a bulk image downloader I use

**Comment by qsniyg** [comment] 2021-02-05 04:51
Thanks for reporting! I'll look into this asap :)

By the way, would `https://pbs.twimg.com/media/Es3w7NrXIAIsf0v.jpg?name=orig` work for you? If so, I could also add a twitter-specific option to do that instead (I could also add an option for `.jpg:orig` if needed, but unless there's something really specific about the addon you're using, I would presume that `.jpg?name=orig` would be preferred)

**Comment by modelfe** [comment] 2021-02-05 04:55
No problem, and thanks for looking into this.

And yes, the format `.jpg?name=orig` works just fine. Thanks also for offering to add this in, much appreciated!

**Comment by qsniyg** [comment] 2021-02-05 05:14
Hmm I can't replicate this (works fine if I add `pbs.twimg.com` to the blacklist), can you send your settings? (using the Export button at the top)

Good point about it not being clear though, thanks for letting me know. It's newline-separated, but I'll elaborate this in the documentation.

**Comment by modelfe** [comment] 2021-02-05 05:31
Sure thing, here you go: https://pastebin.com/92CVNBBT

**Comment by modelfe** [comment] 2021-02-05 05:34
Actually that's the other thing I meant to ask; is there an option to revert all settings to default? I can't remember which other settings I have changed, if any.

**Comment by qsniyg** [comment] 2021-02-05 05:44
Strangely, it works fine even with the settings you sent... Just to test, can you try disabling IMU as a whole (in the extensions/userscript manager page) and see if another addon is causing the redirect?

For resetting to default, import `{}`. Sorry, I know it's not very user-friendly yet, I want to add a "presets" button at some point, which would contain this (alongside a few others, such as an MPIV/Imagus emulation)

I've also added the option :) ("Twitter: Use extension")

**Comment by modelfe** [comment] 2021-02-05 05:49
Hmmm, very strange.

> Just to test, can you try disabling IMU as a whole (in the extensions/userscript manager page) and see if another addon is causing the redirect?

Yes, I have already tried this, and as soon as it's disabled there are no redirects.

I'm using the latest version of the extension on Firefox 85.0 for Linux, if that helps at all.

**Comment by modelfe** [comment] 2021-02-05 05:56
Thanks for adding in the Twitter option, btw! :)

Resetting to default didn't work, though I didn't really expect it would. I wonder if another extension might be interfering in some way. I might try it on a fresh profile and report back.

**Comment by modelfe** [comment] 2021-02-05 06:00
Okay, I tried it on a fresh profile and the problem persists. I wonder if it's OS thing?

**Comment by modelfe** [comment] 2021-02-05 06:04
Another discovery: the blacklist option *does* prevent the "Try to find larger image" context menu option from working. But it doesn't stop redirects when opening the image in a new tab.

**Comment by qsniyg** [comment] 2021-02-05 06:07
Thanks, I'm able to reproduce it now! It's due to the "Do redirection in extension" option being enabled (you may have to set "Show advanced settings" to see it). I thought I had fixed it, but evidently not...

**Comment by qsniyg** [comment] 2021-02-05 06:16
Should be fixed now, thanks again for reporting! :)

**Closed** 2021-02-05 06:15 UTC
Labels: bug, topic:userscript

**Comment by modelfe** [comment] 2021-02-05 06:20
Okay, my apologies for not including browser and OS in the original issue, very poor form!

I'd prefer to leave "Do redirection in extension" enabled, as the automatic redirects in a new tab are much more convenient than using the context option when available, but it sounds like you've got it all working for the next release anyway.

Cheers!

**Comment by qsniyg** [comment] 2021-02-05 06:24
>I'd prefer to leave "Do redirection in extension" enabled

Yeah I was just noting that it was due that option that the issue had occurred, it was definitely a bug. That being said, that option is actually only used for making redirects quicker, as it'll begin redirecting the tab before the content script has finished loading (which can take up to ~70-500ms depending on a number of factors). The option for toggling redirection as a whole is just "Enable redirection" :)

**Comment by modelfe** [comment] 2021-02-05 06:29
Hmmm, that's also strange, because as soon as I switch 'Do redirection in extension' off, I don't get redirects on some other pages either (for example, this VSCO image: https://image-aws-us-west-2.vsco.co/d13012/24209/6019b86b17aa9a3842bfb48d/800x600/vsco6019b86f79481.jpg).

"Enable redirection is still set to yes.

**Comment by qsniyg** [comment] 2021-02-05 07:07
Ah that's an interesting note, didn't think of that. Yeah, if you open it in a new tab, it immediately tries to download the image (due to the server returning a `content-type` header of `binary/octet-stream`, which forces the browser to download it), but the extension ignores this and will redirect it regardless.

Just to be clear however, it should work regardless of that setting for images that don't force download, right? For example:

`http://img.iseephoto.com/files/photos/thumes/2016/07/beautiful-anime-art-1.jpg`

to:

`http://img.iseephoto.com/files/photos/2016/07/beautiful-anime-art-1.jpg`

**Comment by modelfe** [comment] 2021-02-05 07:21
Yes, those examples work as expected, and so do the sites that I have tried now. Who would have thought my sample size of n = 1 for testing earlier would produce an anomaly? :P :)
