### ISSUE TITLE
[Suggestion/bug] Several image scrolling enhancements

### ISSUE THREAD

**Issue by Michael82548** [qsniyg/maxurl#702] opened 2021-04-05 17:25 UTC
Using the unpacked extension v0.18.1 on chromium 89

1. If you are using a laptop and you popup an image and zoom in using the hotkeys on maxurl, you can use the precision touchpad (2 fingers) to scroll anywhere on the image. The problem is when the cursor is outside of the image. Then it stops working.

2. If you move the cursor at all during this, the position of the image resets back to normal.

The potential solution would be to add a "laptop scroll" option, when enabled, it disables issues in *2 which could be checks to where the image position is depending on where the mouse cursor is located. Also, the scroll area is extended outside the image. (Unless you press esc in my case. 

Notes on my solutions.
I have "Disable pointer-events" disabled. Pointer events are required to scroll when the cursor is over the image. This does not prevent the image from snapping back when the cursor moves though.

let me know if you need specific settings that I use. Request the settings and I will provide the values.

**Comment by qsniyg** [comment] 2021-04-05 17:30
Have you tried enabling "Override scroll outside of popup" for 1? I believe it should do what you're looking for :)

I'm not sure I understand the second issue, sorry... could you send your settings? You can use the "Export" button at the top for this.

**Comment by Michael82548** [comment] 2021-04-05 17:37
Basically for issue 2, whenever I move my cursor while I am scrolled to a specific area on the image, it snaps back to the top. You can see this yourself if press the "Popup trigger key" on the image and then hit the "Zoom in key" many times and move your cursor after, the image will snap back to the top. (scrolled all the way up to the top)

If you cannot reproduce this, then I will send the settings.

**Comment by qsniyg** [comment] 2021-04-05 17:54
@Michael82548 Is "Popup panning method" set to Movement? If so, yes I can reproduce it (I'll fix it soon). If not, can you send your settings?

**Comment by Michael82548** [comment] 2021-04-05 18:36
I can reproduce with it set to "movement" and "drag"

**Comment by qsniyg** [comment] 2021-04-05 19:23
@Michael82548 Sorry, I can't reproduce it with drag, so I might be encountering a different issue (though I will fix that one too). Would it be possible for you to send your settings so that I can replicate the issue? Feel free to email them if you'd rather it not be public.

**Comment by Michael82548** [comment] 2021-04-05 20:14
Settings:
{"imu_enabled":true,"language":"en","check_updates":true,"check_update_interval":24,"check_update_notify":true,"dark_mode":true,"settings_tabs":true,"settings_alphabetical_order":false,"settings_visible_description":true,"settings_show_disabled":true,"settings_show_disabled_profiles":false,"settings_show_requirements":true,"advanced_options":true,"allow_browser_request":true,"retry_503_times":2,"retry_503_ms":2500,"use_blob_over_arraybuffer":false,"allow_live_settings_reload":true,"allow_remote":true,"disable_keybind_when_editing":true,"enable_gm_download":true,"gm_download_max":15,"enable_webextension_download":true,"write_to_clipboard":false,"redirect":false,"redirect_video":true,"redirect_audio":false,"redirect_history":false,"redirect_extension":true,"canhead_get":true,"redirect_force_page":true,"redirect_infobox_url":false,"redirect_infobox_timeout":7,"print_imu_obj":false,"redirect_disable_for_responseheader":false,"redirect_to_no_infobox":false,"redirect_host_html":false,"mouseover":true,"mouseover_open_behavior":"popup","t2_mouseover_open_behavior":"popup","t3_mouseover_open_behavior":"popup","mouseover_trigger_behavior":"keyboard","mouseover_trigger_key":[["`"]],"mouseover_trigger_key_t2":[],"mouseover_trigger_key_t3":[],"mouseover_trigger_delay":0.3,"mouseover_trigger_mouseover":false,"mouseover_trigger_enabledisable_toggle":"disable","mouseover_trigger_prevent_key":[["shift"],["ctrl"]],"mouseover_close_behavior":["esc"],"mouseover_close_need_mouseout":true,"mouseover_jitter_threshold":0,"mouseover_cancel_popup_when_elout":true,"mouseover_cancel_popup_with_esc":true,"mouseover_cancel_popup_when_release":true,"mouseover_auto_close_popup":false,"mouseover_auto_close_popup_time":5,"mouseover_hold_key":[["alt"]],"mouseover_hold_position_center":false,"mouseover_hold_close_unhold":false,"mouseover_hold_unclickthrough":true,"mouseover_close_el_policy":"both","mouseover_close_click_outside":true,"mouseover_allow_partial":"media","mouseover_partial_avoid_head":false,"mouseover_use_blob_over_data":false,"popup_use_anonymous_crossorigin":true,"mouseover_enable_notallowed":true,"mouseover_enable_notallowed_cant_load":true,"mouseover_notallowed_duration":400,"mouseover_minimum_size":4,"mouseover_exclude_backgroundimages":false,"mouseover_exclude_page_bg":false,"mouseover_exclude_imagemaps":false,"mouseover_only_links":false,"mouseover_linked_image":true,"mouseover_exclude_sameimage":false,"mouseover_exclude_imagetab":true,"mouseover_allow_video":true,"t2_mouseover_allow_video":true,"t3_mouseover_allow_video":true,"mouseover_allow_audio":false,"t2_mouseover_allow_audio":false,"t3_mouseover_allow_audio":false,"mouseover_allow_hlsdash":true,"t2_mouseover_allow_hlsdash":true,"t3_mouseover_allow_hlsdash":true,"enable_stream_download":false,"stream_mux_mp4_over_mkv":false,"hls_dash_use_max":true,"max_video_quality":null,"mouseover_video_autoplay":true,"mouseover_video_controls":true,"mouseover_video_controls_key":[["*"]],"mouseover_video_loop":true,"mouseover_video_autoloop_max":0,"mouseover_video_playpause_key":[["ctrl","0"]],"mouseover_video_muted":true,"mouseover_video_mute_key":["m"],"mouseover_video_volume":100,"mouseover_video_volume_down_key":[["down"]],"mouseover_video_volume_up_key":[["up"]],"mouseover_video_volume_change_amt":5,"mouseover_video_resume_from_source":true,"mouseover_video_resume_if_different":false,"mouseover_video_pause_source":true,"mouseover_video_seek_amount":10,"mouseover_video_seek_left_key":[["*"]],"mouseover_video_seek_right_key":[["*"]],"mouseover_video_frame_prev_key":[["*"]],"mouseover_video_frame_next_key":[["*"]],"mouseover_video_framerate":30,"mouseover_video_speed_down_key":[["*"]],"mouseover_video_speed_up_key":[["*"]],"mouseover_video_speed_amount":0.1,"mouseover_video_reset_speed_key":[["*"]],"mouseover_video_screenshot_key":["shift","s"],"popup_video_screenshot_format":"png","mouseover_ui":true,"mouseover_ui_toggle_key":["u"],"mouseover_ui_opacity":80,"mouseover_ui_use_safe_glyphs":false,"mouseover_ui_imagesize":true,"mouseover_ui_zoomlevel":true,"mouseover_ui_filesize":true,"mouseover_ui_gallerycounter":true,"mouseover_ui_gallerymax":50,"mouseover_ui_gallerybtns":true,"mouseover_ui_closebtn":true,"mouseover_ui_optionsbtn":false,"mouseover_ui_downloadbtn":true,"mouseover_ui_rotationbtns":true,"mouseover_ui_caption":true,"mouseover_ui_wrap_caption":true,"mouseover_ui_caption_link_page":true,"mouseover_ui_link_underline":true,"mouseover_use_remote":false,"mouseover_zoom_behavior":["fit"],"mouseover_zoom_custom_percent":100,"mouseover_zoom_max_width":0,"mouseover_zoom_max_height":0,"mouseover_pan_behavior":"drag","mouseover_movement_inverted":true,"mouseover_drag_min":5,"mouseover_scrolly_behavior":["pan"],"mouseover_scrollx_behavior":["pan"],"mouseover_scrolly_video_behavior":"default","mouseover_scrolly_video_invert":false,"mouseover_scrollx_video_behavior":"default","scroll_override_page":false,"scroll_zoom_origin":"cursor","scroll_zoom_behavior":"incremental","scroll_incremental_mult":1.25,"mouseover_move_with_cursor":true,"mouseover_move_within_page":true,"zoom_out_to_close":false,"scroll_past_gallery_end_to_close":false,"mouseover_position":["center"],"mouseover_prevent_cursor_overlap":true,"mouseover_add_link":true,"mouseover_add_video_link":true,"mouseover_click_image_close":false,"mouseover_click_video_close":false,"mouseover_download":false,"mouseover_hide_cursor":false,"mouseover_hide_cursor_after":0,"mouseover_mouse_inactivity_jitter":5,"mouseover_clickthrough":false,"mouseover_mask_ignore_clicks":false,"mouseover_links":true,"mouseover_only_valid_links":true,"mouseover_allow_self_pagelink":false,"mouseover_allow_iframe_el":true,"mouseover_allow_canvas_el":false,"mouseover_allow_svg_el":false,"mouseover_enable_gallery":true,"mouseover_gallery_cycle":false,"mouseover_gallery_prev_key":[["j"]],"mouseover_gallery_next_key":[["l"]],"mouseover_gallery_move_after_video":false,"mouseover_gallery_download_key":["shift","d"],"gallery_download_unchanged":true,"gallery_zip_filename_format":"{host_domain_nosub}-{items_amt}-{download_unix}\n{items_amt}-{download_unix}","gallery_zip_add_tld":false,"gallery_zip_add_info_file":true,"mouseover_styles":"","mouseover_enable_fade":true,"mouseover_enable_zoom_effect":true,"mouseover_zoom_effect_move":false,"mouseover_fade_time":100,"mouseover_enable_mask_styles2":"never","mouseover_mask_styles2":"background-color: rgba(0, 0, 0, 0.5)","mouseover_mask_fade_time":100,"mouseover_ui_styles":"","mouseover_wait_use_el":false,"mouseover_add_to_history":false,"mouseover_close_key":["esc"],"mouseover_download_key":[["alt","s"]],"mouseover_open_new_tab_key":[["t"]],"mouseover_open_bg_tab_key":[["alt","t"]],"mouseover_copy_link_key":["shift","c"],"mouseover_open_options_key":[["ctrl","alt","o"]],"mouseover_open_orig_page_key":[["s"]],"mouseover_rotate_left_key":["e"],"mouseover_rotate_right_key":["r"],"mouseover_flip_horizontal_key":[["["]],"mouseover_flip_vertical_key":[["'"]],"mouseover_zoom_in_key":[["2"]],"mouseover_zoom_out_key":[["1"]],"mouseover_zoom_full_key":[["4"]],"mouseover_zoom_fit_key":[["3"]],"mouseover_fullscreen_key":["f"],"mouseover_apply_blacklist":false,"apply_blacklist_host":true,"mouseover_matching_media_types":false,"mouseover_find_els_mode":"hybrid","popup_allow_cache":true,"popup_cache_duration":30,"popup_cache_itemlimit":20,"popup_cache_resume_video":true,"website_inject_imu":true,"website_image":true,"extension_contextmenu":true,"extension_hotreload":true,"allow_watermark":false,"allow_smaller":false,"allow_possibly_different":false,"allow_possibly_broken":false,"allow_possibly_upscaled":false,"allow_thirdparty":false,"allow_apicalls":true,"allow_thirdparty_libs":true,"custom_xhr_for_lib":false,"allow_thirdparty_code":false,"allow_bruteforce":false,"process_format":{},"deviantart_prefer_size":false,"deviantart_support_download":true,"ehentai_full_image":true,"imgur_filename":true,"imgur_source":true,"instagram_use_app_api":false,"instagram_dont_use_web":false,"instagram_prefer_video_quality":true,"instagram_gallery_postlink":false,"snapchat_orig_media":true,"tiktok_no_watermarks":false,"tiktok_thirdparty":null,"tumblr_api_key":"NULL","twitter_use_ext":false,"bigimage_blacklist":"","bigimage_blacklist_engine":"glob","filename_format":"{author_username} {filename}","replaceimgs_enable_keybinding":true,"replaceimgs_keybinding":[["ctrl","\\"]],"replaceimgs_auto":false,"replaceimgs_replaceimgs":true,"replaceimgs_addlinks":true,"replaceimgs_replacelinks":true,"replaceimgs_plainlinks":"none","replaceimgs_links_newtab":false,"replaceimgs_remove_size_constraints":false,"replaceimgs_usedata":false,"replaceimgs_wait_fullyloaded":false,"replaceimgs_totallimit":8,"replaceimgs_domainlimit":3,"replaceimgs_delay":1,"replaceimgs_css":"","replaceimgs_simple_progress":true,"highlightimgs_enable_keybinding":false,"highlightimgs_keybinding":["shift","alt","h"],"highlightimgs_enable":false,"highlightimgs_auto":"hover","highlightimgs_onlysupported":true,"highlightimgs_css":"outline: 3px double yellow","last_update_check","last_update_version":"0.18.1","last_update_url":null,"allow_video":true,"mouseover_enable_mask_styles":false,"mouseover_support_pointerevents_none":false,"settings_version":10}

**Comment by Michael82548** [comment] 2021-04-06 15:21
Can you reproduce it now?

**Comment by qsniyg** [comment] 2021-04-06 23:22
Sorry for the late reply. Yes I can reproduce it, it's due to the "Move with cursor" option.

Is there a reason you have it enabled? I believe the "Movement" option (for "Popup panning method") should do the trick if you're interested in the functionality, "Move with cursor" was mostly meant for the mouseover trigger (rather than keyboard). In fact, iirc it was disabled a while ago for the keyboard trigger (I enabled it again as it didn't conflict with anything, though I still don't see a use case... if there is one, please let me know :)

**Comment by Michael82548** [comment] 2021-04-07 03:26
Its fixed after disabling "Move with cursor"

Thank you!

**Comment by qsniyg** [comment] 2021-04-07 03:27
Great! I'll close the issue then :)

**Closed by qsniyg** 2021-04-07 03:27 UTC
