### ISSUE TITLE
After enabling `Clicking link downloads`, the downloaded images are not the largest

### ISSUE THREAD

**Issue by liraqb** [qsniyg/maxurl#288] opened 2020-04-11 00:04 UTC
After enabling `Clicking link downloads`, the pictures downloaded on Youtube are not the largest pictures, but the smaller pictures currently popping up.

**Comment by qsniyg** [comment] 2020-04-11 08:36
Thanks for reporting! Interesting... are you sure the issue is related though? The only part of the code that option changes is how the `<a>` link is handled, it shouldn't affect the rules in any way.

Could you give me an example of an image that isn't changed to its largest version? So far I can't replicate it..

Is "Possibly different images" enabled by the way? Also, make sure "Videos" is disabled (or "Don't popup video for image" is enabled) when testing to avoid it popping up the video instead.

**Comment by liraqb** [comment] 2020-04-11 09:34
Yes, I have not enabled "Possibly different images". No problem now.

**Comment by qsniyg** [comment] 2020-04-11 09:37
Awesome! I'll close this issue then :)

To be honest, I should probably just remove the need for that option, it's so rare (and I believe it's a cache error on their side) that I don't think it's really worth keeping it under that option.

**Closed by qsniyg** 2020-04-11 09:37 UTC
Labels: bug, topic:userscript
