### ISSUE TITLE
Bug in user script - Closes Firefox

### ISSUE THREAD

**Issue by Jimmy03** [qsniyg/maxurl#200] opened 2020-01-21 01:04 UTC
https://www.reddit.com/r/firefox/comments/erl8jx/firefox_closes_on_some_reddit_pages_when_using/

**Comment by qsniyg** [comment] 2020-01-21 01:16
Wow it _definitely_ shouldn't be doing that. There's no code related to closing a window or tab in the script...

I'm trying to replicate the issue, but so far I'm failing... I'm going to an image subreddit (e.g. /r/pics) on old reddit, I open the image in the new tab, and as you say, it opens a popup for the cross-origin request. After clicking "Allow once", it closes the popup, then redirects to the image. Even if I close the image tab and go back to the subreddit, it doesn't seem to misbehave in any way...

Could you record a video of what causes the crash?

Thanks for reporting, and I'm sorry this is happening!

---

I'm _guessing_ is an issue in Tampermonkey (to be honest, I haven't tested the userscript much using Tampermonkey), but I'll see if I can fix it on my end. If not, then if I can reproduce the issue, I'll be hopefully be able to find the cause and report it properly to the Tampermonkey developer.

Just to test, could you try either Violentmonkey, or the [Firefox addon](https://addons.mozilla.org/en-US/firefox/addon/image-max-url/), and see if you still have the same issue?

**Comment by Jimmy03** [comment] 2020-01-21 02:45
I don't think Tampermonkey is the issue, because when I disable your script Firefox doesn't crash.  
It has only happened since mid January, before that it was ok, so what changed around version 0.12.5?

Also it's weird that Tampermonkey can't update to 0.12.6

**Comment by Jimmy03** [comment] 2020-01-21 03:18
Weird I was browsing reddit and this page opened up, is this something to do with the bot?
https://i.imgur.com/LqJwrRm.png

**Comment by qsniyg** [comment] 2020-01-21 11:49
@Jimmy03

>It has only happened since mid January

Interesting, and you're right, Tampermonkey hasn't been updated since November, so it definitely is something with the script. The problem is, [a lot changed](https://greasyfork.org/en/scripts/36662-image-max-url/diff?v1=765121&v2=761868) in the January releases (0.12.2 to 0.12.5), so it's a little bit difficult to pin down the precise issue without being able to reproduce it on my side...

>Open the image in same tab, not new tab

Do you mean the popup (e.g. pressing Shift+Alt+I on the image)? Or right clicking on the image, and clicking "View Image"?

>Also it's weird that Tampermonkey can't update to 0.12.6

Hmm, I don't know why either, but you can update it manually: https://greasyfork.org/scripts/36662-image-max-url/code/Image%20Max%20URL.user.js

>a page opened up for me to compose a message to MAXImagebot with delete some reddit post, is this something with the bot?

This happens if you click on the "remove" link from one of the posts the bot commented on, it shouldn't be related :) (If it is related, then I'm _very_ confused haha)

---

Could you record a video of how to create the crash? I'm still unable to reproduce it, so this would show me how to do it :)

**Comment by qsniyg** [comment] 2020-01-21 17:36
@Jimmy03 I tried pretty much every way I could think of (opening a popup through Shift+Alt+I, clicking the link then going back and reloading, opening it through View Image, etc.), I couldn't reproduce the issue you had with 0.12.5, and I set the about:config settings to what you specified.

Here's a video of what I did: https://photos.app.goo.gl/P7yzzZYHX34qFAZXA I tried a few other ways before recording the video as well. Did I replicate it wrong?

Just in case, could you try temporarily disabling all other extensions/userscripts other than Tampermonkey and Image Max URL, to see if the issue still exists? There's been a few times where there's been a conflict between this userscript and another that caused strange issues that I wasn't able to replicate on my end.

**Comment by Jimmy03** [comment] 2020-01-21 18:11
In the video I don't right-click the image and view it.
You have to click the image on the sub itself not in the thread.
Like when you browse the sub there are threads with images next to them, when I click the image it loads the image not the thread.

**Comment by qsniyg** [comment] 2020-01-21 18:18
@Jimmy03 Gotcha, like this then? https://photos.app.goo.gl/RKPyoc1Lhg1J1XAG9

I still can't seem to reproduce the issue...

**Comment by Jimmy03** [comment] 2020-01-21 18:26
Yes, except when I do it, it opens the Tampermonkey Window in a new tab like you , but also the image will be opened in a second tab where your script takes effect and maximizes the image.

**Comment by qsniyg** [comment] 2020-01-21 18:37
>but also the image will be opened in a second tab where your script takes effect and maximizes the image

So it maximizes the image _before_ you click "Allow once"? That definitely shouldn't happen... In fact, due to the bug in Tampermonkey, it actually shouldn't be able to maximize the image at all (at least it doesn't for me, unless I use the git master version).

Could you let me know these 3 things?

 * Can you give me a link for an image that the userscript is able to redirect to a larger version of?
 * Which version of Tampermonkey are you running? You can find this by right-clicking the icon and selecting "Manage Extension". I'm running 4.10.6105
 * Did you modify the options for the userscript? If so, could you paste your exported settings? (the Export button is at the top of [the options page](https://qsniyg.github.io/maxurl/options.html))

**Comment by Jimmy03** [comment] 2020-01-21 20:21
I think you're right the maximize feature isn't working, I checked a couple times.

Tampermonkey version 4.10.6105

I didn't modify any options in the user script

**Comment by qsniyg** [comment] 2020-01-21 20:24
@Jimmy03 Alright, so it seems we're on pretty much the same configuration here... Can you try temporarily disabling all other addons/userscripts to see if the issue still occurs?

I know this issue only happens when Image Max URL is enabled, but I'm wondering if it's due to a conflict with another addon or userscript.

**Comment by Jimmy03** [comment] 2020-01-21 20:32
These are my addons

Adblock Plus
Context Search
Noscript
RSSPreview
Search by Image
Tampermonkey

I don't want to disable ABP or Noscript for security reasons

The only other user script is Flickr Original Link, and the crash still happens when I disabled it.

**Comment by Jimmy03** [comment] 2020-01-21 20:39
In Firefox I have open links in Tabs instead of new windows option enabled

**Comment by qsniyg** [comment] 2020-01-21 20:43
@Jimmy03 So I installed everything (see below), and the "Open links in tabs" setting is also set, but again, no crash...

![addons](https://user-images.githubusercontent.com/20496822/72841446-3b1a1400-3c4b-11ea-8fe0-378c3627c0e5.png)

Could you try the [firefox addon](https://addons.mozilla.org/en-US/firefox/addon/image-max-url/), and see if that works instead? Make sure the userscript in Tampermonkey (or Tampermonkey entirely) is disabled while testing.

**Comment by Jimmy03** [comment] 2020-01-21 21:06
I don't want to install any more addons in case it messes up my configuration, but I'm pretty sure it's related to Tampermonkey

**Comment by qsniyg** [comment] 2020-01-21 21:14
@Jimmy03 I don't think the addon should mess up your configuration, as it doesn't touch the browser at all, it's actually just a very thin layer over the userscript (https://github.com/qsniyg/maxurl/blob/master/extension/background.js, the bulk of the code resides in XHR handling)

In any case, I think you're right, I honestly have absolutely no idea what would be the cause of the issue (there's no code in either the userscript or the addon that should close anything), and I've never experienced it before (I don't personally use Tampermonkey since it's both obfuscated and proprietary, so I'm not sure if I can trust it).

If you have the time, would you mind trying older versions of the userscript (https://greasyfork.org/en/scripts/36662-image-max-url/versions, click on the version, then click "Downgrade to version ..."), to find what the last working version is? That way I'll hopefully be able to narrow down what might have caused the issue and fix it :)

**Comment by Jimmy03** [comment] 2020-01-21 21:17
Yeah I don't want to do too much bug testing with the browser since I need it clean and working, but I will keep looking for what it might be.

**Comment by Jimmy03** [comment] 2020-01-21 21:34
This should help:

0.11.19 good, doesn't show tampermonkey tab
0.12.0 crash, shows tampermonkey tab, and then crashes when the Tampermonkey Timer reaches zero

**Comment by Jimmy03** [comment] 2020-01-21 22:07
That causes the same crash, opens the tampermonkey tab, and the image in a second tab, and then crashes when the tampermonkey timer reaches 0

**Comment by qsniyg** [comment] 2020-01-21 22:24
@Jimmy03 So here are 3 different tests:

https://gist.github.com/qsniyg/88f185bb3bf6a0f306dffa48d69fcc2f/raw/55be51fed9bf8001ec02749d76bf9f3006d246f1/test1.user.js (disables `onprogress`)

https://gist.github.com/qsniyg/88f185bb3bf6a0f306dffa48d69fcc2f/raw/55be51fed9bf8001ec02749d76bf9f3006d246f1/test2.user.js (disables `abort()`)

https://gist.github.com/qsniyg/88f185bb3bf6a0f306dffa48d69fcc2f/raw/55be51fed9bf8001ec02749d76bf9f3006d246f1/test3.user.js (disables both `onprogress` and `abort()`)

Maybe try the third one first, as if that one crashes, the first two will also crash. If it doesn't crash though, could you let me know which of the first two crashes?

**Comment by Jimmy03** [comment] 2020-01-21 22:50
The 3rd one crashes in the same way

**Comment by qsniyg** [comment] 2020-01-21 23:09
@Jimmy03 Odd, now I'm really confused as to what the cause is... Anyways, here's another one, which shouldn't crash, but also won't do anything. Open the console (F12), then when it's finished, right click and select Export Visible Messages to -> Clipboard, then paste it here (or on pastebin). It contains a lot of debug information that might be able to help me figure out what the issue is. I have genuinely no idea what is going on.

https://gist.github.com/qsniyg/9065cb574178953b9a1007004021ff9d/raw/1d419280aa1b8250a2e044a2b1769295859dfe66/test4.user.js

**Comment by Jimmy03** [comment] 2020-01-21 23:57
The console remains empty, I did the whole process.

At least you know it's something between 0.11.19 and 0.12.0

**Comment by qsniyg** [comment] 2020-01-22 00:00
@Jimmy03 In that case, there must have been an error while installing the userscript, or it's not running, as it should output a lot, from before it even starts the XHR. Try opening a new tab, opening the console (F12), then going to: https://i.imgur.com/Xm9UN7Sr.jpg. If it doesn't show any output, then the script is likely not properly installed, or that specific version isn't running.

**Comment by Jimmy03** [comment] 2020-01-22 00:03
When the Tampermoneky Tab loads the console gets cleared, I'll try that image

**Comment by Jimmy03** [comment] 2020-01-22 00:12
I think I have an idea of what might be happening.

Once the Tampermonkey tab closes and it's the last tab open it will closes Friefox because no tabs are left.

I tried 0.12.5 again but this time I opened several other tabs also, then I did my usual test on reddit but this time it didn't close Firefox because other tabs were still present I'm guessing.

**Comment by qsniyg** [comment] 2020-01-22 00:17
@Jimmy03 Ah, so the test then is:

 * Open an image in a tab
 * Tampermonkey opens a "cross origin request" tab
 * Close the image tab
 * Wait until the timeout is finished, and then since it's the last tab, it closes Firefox

Is this correct? In which case, yes, that makes sense :)

What doesn't make sense though, is that this only happens in 0.12.0+... unless you mean that 0.11.19 doesn't pop up the Tampermonkey window?

**Comment by Jimmy03** [comment] 2020-01-22 00:18
Yes that is the process, and 0.11.19 doesn't show the tampermonkey tab.

I only see the Tampermonkey countdown message in a Tab, not a new window, probably because of how I configured all links to open in tabs.

**Comment by qsniyg** [comment] 2020-01-22 00:20
Cool! So therefore it's not an issue with this script, correct?

By the way, you can prevent it from popping up in the future by setting "Always allow all domains" :)

**Comment by Jimmy03** [comment] 2020-01-22 00:43
That may not be the most secure option, but yeah.
I will let you know if there are any further issues.

**Comment by qsniyg** [comment] 2020-01-22 00:44
Alright, I'll close this issue then. Feel free to open another issue if you encounter any more problems though :)

**Closed by qsniyg** 2020-01-22 00:44 UTC
Labels: bug, topic:userscript
