### ISSUE TITLE
History of objects still present even if include_pastobjs is disabled

### ISSUE THREAD

**Issue by rEnr3n** [qsniyg/maxurl#106] opened 2019-08-22 05:42 UTC
index.js
```
var maximage = require('/home/maxurl/userscript.user.js');
var smallimage = process.argv[2]
//smallimage = 'https://pbs.twimg.com/media/ECG-2SHXYAA4Mnk.jpg';

maximage(smallimage, {
  // If set to false, it will return only the URL if there aren't any special properties
  fill_object: true,

  // Maximum amount of times it should be run.
  //  Recommended to be at least 5
  iterations: 200,

  // Whether or not to store to, and use an internal cache
  use_cache: true,

  // List of "problems" (such as watermarks or possibly broken image) to exclude.
  //   By default, all problems are excluded.
  //   By setting it to [], no problems will be excluded.
  exclude_problems: [ "smaller", "possibly_different", "possibly_broken" ],

  // This will include a "history" of objects found through iterations.
  //   Disabling this will only keep the objects found through the last successful iteration.
  include_pastobjs: false,

  // This will try to find the original page for an image, even if it requires extra requests.
  // Currently only applies to Flickr.
  force_page: false,

  // This is useful for implementing a blacklist or whitelist.
  // If unspecified, it accepts all URLs.
  filter: function(url) {
    return true;
  },

  // Helper function to perform HTTP requests, used for sites like Flickr
  //  The API is expected to be like GM_xmlHTTPRequest's API.
  // An implementation using node's request module can be found in bot.js
  do_request: function(options) {
    // options = {
    //   url: "",
    //   method: "GET",
    //   headers: {}, // If a header is null or "", don't include that header
    //   onload: function(resp) {
    //     // resp is expected to be XMLHttpRequest-like object, implementing these fields:
    //     //   finalUrl
    //     //   readyState
    //     //   responseText
    //     //   status
    //   }
    // }
  },

  // Callback
  cb: function(result) {
    if (!result)
      return;

    if (result.length === 1 && result[0].url === smallimage) {
       // No larger image was found
       return;
    }

    for (var i = 0; i < result.length; i++) {
	    console.log(result[i].url);
	    //console.log(result);
    }
  }
});
```

Running `node ren.js 'http://img.hankyung.com/photo/201808/ZK.17491055.3.jpg'` results to:
```
http://img.hankyung.com/photo/201808/ZK.17491055.4.jpg
http://img.hankyung.com/photo/201808/ZK.17491055.1.jpg
```

Looking at the full result:
```
[ { url: 'http://img.hankyung.com/photo/201808/ZK.17491055.4.jpg',
    always_ok: false,
    likely_broken: false,
    can_head: true,
    head_ok_errors: [],
    head_wrong_contenttype: false,
    head_wrong_contentlength: false,
    waiting: false,
    redirects: false,
    forces_download: false,
    is_private: false,
    is_original: false,
    norecurse: false,
    bad: false,
    fake: false,
    headers: {},
    extra: {},
    filename: '',
    problems: { watermark: false, smaller: false } },
  { url: 'http://img.hankyung.com/photo/201808/ZK.17491055.1.jpg',
    always_ok: false,
    likely_broken: false,
    can_head: true,
    head_ok_errors: [],
    head_wrong_contenttype: false,
    head_wrong_contentlength: false,
    waiting: false,
    redirects: false,
    forces_download: false,
    is_private: false,
    is_original: false,
    norecurse: false,
    bad: false,
    fake: false,
    headers: {},
    extra: {},
    filename: '',
    problems: { watermark: false, smaller: false } } ]
[ { url: 'http://img.hankyung.com/photo/201808/ZK.17491055.4.jpg',
    always_ok: false,
    likely_broken: false,
    can_head: true,
    head_ok_errors: [],
    head_wrong_contenttype: false,
    head_wrong_contentlength: false,
    waiting: false,
    redirects: false,
    forces_download: false,
    is_private: false,
    is_original: false,
    norecurse: false,
    bad: false,
    fake: false,
    headers: {},
    extra: {},
    filename: '',
    problems: { watermark: false, smaller: false } },
  { url: 'http://img.hankyung.com/photo/201808/ZK.17491055.1.jpg',
    always_ok: false,
    likely_broken: false,
    can_head: true,
    head_ok_errors: [],
    head_wrong_contenttype: false,
    head_wrong_contentlength: false,
    waiting: false,
    redirects: false,
    forces_download: false,
    is_private: false,
    is_original: false,
    norecurse: false,
    bad: false,
    fake: false,
    headers: {},
    extra: {},
    filename: '',
    problems: { watermark: false, smaller: false } } ]
```

There are two lists. One of them is a duplicate. Also, `watermark` is `false` which I believe should be `true`.

**Comment by qsniyg** [comment] 2019-08-22 05:59
Huh that's odd... I only see it happen once if I add `console.log(result)` to the beginning of `cb`. Can you confirm this is how you logged it?

Also sorry, I didn't explain the 'watermark' problem correctly. It will only set that attribute to true if the larger image _adds_ a watermark to the image (where the smaller one doesn't have one).

**Comment by rEnr3n** [comment] 2019-08-22 06:37
> Huh that's odd... I only see it happen once if I add `console.log(result)` to the beginning of `cb`. Can you confirm this is how you logged it?

Yes.

> Also sorry, I didn't explain the 'watermark' problem correctly. It will only set that attribute to true if the larger image _adds_ a watermark to the image (where the smaller one doesn't have one).

By your definition, shouldn't `watermark` be set to `true` then?

**Comment by qsniyg** [comment] 2019-08-22 06:48
>Yes.

Odd... I only have it show once with this code:

```
var maximage = require('/home/maxurl/userscript.user.js');
var smallimage = process.argv[2]
//smallimage = 'https://pbs.twimg.com/media/ECG-2SHXYAA4Mnk.jpg';

maximage(smallimage, {
  // If set to false, it will return only the URL if there aren't any special properties
  fill_object: true,

  // Maximum amount of times it should be run.
  //  Recommended to be at least 5
  iterations: 200,

  // Whether or not to store to, and use an internal cache
  use_cache: true,

  // List of "problems" (such as watermarks or possibly broken image) to exclude.
  //   By default, all problems are excluded.
  //   By setting it to [], no problems will be excluded.
  exclude_problems: [ "smaller", "possibly_different", "possibly_broken" ],

  // This will include a "history" of objects found through iterations.
  //   Disabling this will only keep the objects found through the last successful iteration.
  include_pastobjs: false,

  // This will try to find the original page for an image, even if it requires extra requests.
  // Currently only applies to Flickr.
  force_page: false,

  // This is useful for implementing a blacklist or whitelist.
  // If unspecified, it accepts all URLs.
  filter: function(url) {
    return true;
  },

  // Helper function to perform HTTP requests, used for sites like Flickr
  //  The API is expected to be like GM_xmlHTTPRequest's API.
  // An implementation using node's request module can be found in bot.js
  do_request: function(options) {
    // options = {
    //   url: "",
    //   method: "GET",
    //   headers: {}, // If a header is null or "", don't include that header
    //   onload: function(resp) {
    //     // resp is expected to be XMLHttpRequest-like object, implementing these fields:
    //     //   finalUrl
    //     //   readyState
    //     //   responseText
    //     //   status
    //   }
    // }
  },

  // Callback
  cb: function(result) {
    console.log(result);
    if (!result)
      return;

    if (result.length === 1 && result[0].url === smallimage) {
       // No larger image was found
       return;
    }

    for (var i = 0; i < result.length; i++) {
	    console.log(result[i].url);
	    //console.log(result);
    }
  }
});
```

If your code is any different from this, could you share it? Sorry, otherwise I'm unable to reproduce this issue at the moment.

>By your definition, shouldn't watermark be set to true then?

Ah fair enough, I just checked the original image again. However, it seems to be that the section where the watermark is has been cropped in the `.3` image (if you look at http://img.hankyung.com/photo/201902/01.19032633.1.jpg, there is no watermark, so it doesn't appear that `.1` adds a watermark).

**Comment by rEnr3n** [comment] 2019-08-22 07:10
I think I misinterpreted what you said. I tested your code. But I still get a history.

```
[ { url: 'http://img.hankyung.com/photo/201808/ZK.17491055.4.jpg',
    always_ok: false,
    likely_broken: false,
    can_head: true,
    head_ok_errors: [],
    head_wrong_contenttype: false,
    head_wrong_contentlength: false,
    waiting: false,
    redirects: false,
    forces_download: false,
    is_private: false,
    is_original: false,
    norecurse: false,
    bad: false,
    fake: false,
    headers: {},
    extra: {},
    filename: '',
    problems: { watermark: false, smaller: false } },
  { url: 'http://img.hankyung.com/photo/201808/ZK.17491055.1.jpg',
    always_ok: false,
    likely_broken: false,
    can_head: true,
    head_ok_errors: [],
    head_wrong_contenttype: false,
    head_wrong_contentlength: false,
    waiting: false,
    redirects: false,
    forces_download: false,
    is_private: false,
    is_original: false,
    norecurse: false,
    bad: false,
    fake: false,
    headers: {},
    extra: {},
    filename: '',
    problems: { watermark: false, smaller: false } } ]
http://img.hankyung.com/photo/201808/ZK.17491055.4.jpg
http://img.hankyung.com/photo/201808/ZK.17491055.1.jpg
```

**Comment by qsniyg** [comment] 2019-08-22 07:21
Ahhh now I understand the issue. Sorry I thought the issue was that the array was being printed twice.

In that case, those are 2 different possible URLs. The first is the larger one, but it might not work (and in this case, it doesn't). The second is another possible URL that is still expected to be larger than the one you inputted, but it isn't as large as the first. This isn't the history however, as it is still part of the same iteration. Here is the source to show what I mean (line 1631 in git master):

```
return [
    src.replace(/\.[0-9](\.[^/.]*)$/, ".4$1"),
    src.replace(/\.[0-9](\.[^/.]*)$/, ".1$1")
];
```

On a sidenote, there is a function (bigimage_recursive_loop) that will check URLs to see if they work, and only output the ones that do, but it requires a way to query the images, and I haven't yet exposed it to the node API and documented it properly. I'll try to do it soon, but in the meantime, you can use the code in bot.js for that (the `dourl` function).

I'll close this issue as I believe both of the issues you reported have been addressed, but feel free to reopen or comment if not :)

**Closed by qsniyg** 2019-08-22 07:21 UTC
Labels: bug
