### ISSUE TITLE
[twitter] always forcing png since 0.11.14

### ISSUE THREAD

**Issue by Kattus** [qsniyg/maxurl#168] opened 2019-12-03 19:32 UTC
Hi, noticed since upgrading to 0.11.14 (tried downgrading and it fixed it) when I open any jpg picture on twitter it will redirect to a png that doesn't exist. This is obviously extremely annoying as I have to manually change it back to jpg every single time, which kind of defeats the purpose of this addon.

Using the firefox addon on Firefox 71.0 if that matters.

URL to test with (SFW): https://pbs.twimg.com/media/EK3eZtaVAAAB256?format=jpg&name=900x900

**Comment by qsniyg** [comment] 2019-12-04 00:45
Do you have tracking protection set to high/strict? If so, this is likely the same as #167.

I've "fixed" it by disabling redirect if tracking protection blocks it, but I'll try to see if I can add a slightly better option, as it does work if the request is sent client-side.

**Comment by qsniyg** [comment] 2019-12-04 01:54
I'll close this issue pre-emptively as I believe it's fixed in 0.11.15.

Please feel free to reopen the issue if it still exists though.

**Comment by Kattus** [comment] 2019-12-04 12:08
It still happens with 0.11.15, it works as expected if I disable tracking protection (though I feel that's not an acceptable solution). I guess I'll stay on 0.11.13 for now.

Also I cannot re-open this, probably because you (a higher power) closed it :P

**Comment by qsniyg** [comment] 2019-12-04 12:47
Weird... Could you try sideloading the attached version (about:debugging -> This Firefox -> Load Temporary Add-on, after extracting the zip file), opening a new tab and pressing F12 to open the console, make sure Persist Logs is checked, then go to https://pbs.twimg.com/media/EK2OTJ3WoAABdYR.jpg, and once it's done, right click on the console and select Export visible messages to -> File, then upload the file here? It has a bunch of logging, which might help narrow down the issue somewhat.

[extension.xpi.zip](https://github.com/qsniyg/maxurl/files/3921823/extension.xpi.zip)

**Comment by Kattus** [comment] 2019-12-04 16:44
It seems to sometimes work, but 90% of the time it will just force png as previously mentioned.
Here's the log: [console-export-2019-12-4_17-42-52.txt](https://github.com/qsniyg/maxurl/files/3922950/console-export-2019-12-4_17-42-52.txt)

**Comment by qsniyg** [comment] 2019-12-05 02:42
@Kattus I still can't reproduce it, even with the method you've sent, sorry. 
I also really have no idea why it would work when opening in a new tab without switching to it...

Two things:

The log you sent was run when the URL was https://pbs.twimg.com/media/EK2OTJ3WoAABdYR.png?name=orig, so I unfortunately can't really get any useful information (I'm mainly looking for the response headers). Could you open an empty new tab, open the console (and make sure Persist Logs is enabled, you can find the option in the Settings cog on the right), and then go to the link with the console open? This will make sure the entire log is shown (the log should be at least twice as large).

Second, would you mind sending me your prefs.js file in ~/.mozilla/firefox/(profile)? This will (hopefully) let me replicate your browser's configuration.

If I can't figure out a proper solution soon, I'll just add an option to disable browser requests, which _should_ fix the issue of redirecting to a broken image (although it will prevent redirection for Twitter etc. when tracking protection is enabled). Hopefully the proper solution will be found though. Thanks for reporting and helping out with debugging :)

**Comment by Kattus** [comment] 2019-12-05 12:17
I did react to it directly saying I opened the "redirected" image, but I really *did* open the proper link, though it seems I didn't understand "Persist logs", I had pressed it in another tab but it didn't transfer over to the Console tab, I found the correct one now.

The log did however not get double the length, in fact it ended up even smaller! (but at least it now shows the correct link I guess)

Here's the three files you requested:
[files.zip](https://github.com/qsniyg/maxurl/files/3926760/files.zip)

Also no thank *you* for making this script :)

**Comment by qsniyg** [comment] 2019-12-05 14:37
@Kattus

I think I see the issue now:

```
Navigated to https://pbs.twimg.com/media/EK2OTJ3WoAABdYR.jpg
GEThttps://pbs.twimg.com/media/EK2OTJ3WoAABdYR.jpg
https://pbs.twimg.com/media/EK2OTJ3WoAABdYR.png?name=orig userscript.html:29045:15
```

This is done before the debug version of extension I sent is even run. The one I sent is supposed to print out a bunch of debug logs before being able to find the `.png?name=orig` URL (which it does, but only _after_ it has been redirected).

This likely means you have another instance of the addon or the script running, which also explains the weird timing issue you mentioned earlier (where it would only work if you didn't open the tab while it was loading). Check in about:addons to see if you have another instance of the extension installed, and if so, disable or remove it. If you have the userscript installed, disable or remove that as well. 

See if it works :) If not, could you send the console log again? (this time, only with the one version of the addon enabled)

**Comment by Kattus** [comment] 2019-12-05 14:59
Oh god.. I feel like such an idiot right now, I was damn sure I had removed the userscript version long ago.. That's what I get >_>

Disabled the userscript version (which btw was indeed updated) and it works now.
Though I also tried disabling the browser extension, and the userscript version is still broken.. so idk if I should close this or not :P

**Comment by qsniyg** [comment] 2019-12-05 15:00
@Kattus Awesome! Yeah that should be fixed in the next update (https://github.com/qsniyg/maxurl/commit/1476501fd860849348dd60e29b19fa6e2c461014), hopefully tomorrow :)

And no worries, I've done the same mistake a ton of times before while testing this haha.

**Closed by qsniyg** 2019-12-05 15:00 UTC
Labels: browser:firefox, bug, topic:userscript
