### ISSUE TITLE
Add support for lookahead and cache previous results

### ISSUE THREAD

**Issue by lnp5131** [qsniyg/maxurl#416] opened 2020-08-30 11:53 UTC
This would reduce the delay while browsing. Also, the cache should persist between popup instances on the same page.

**Comment by qsniyg** [comment] 2020-08-30 11:58
Agreed, this would be super helpful. Related to: https://github.com/qsniyg/maxurl/issues/151

It does cache the rules (helpful for e.g. sites like Flickr, where to find a larger image, it requires multiple api calls), but it doesn't cache the images or videos themselves.

In theory this shouldn't be _too_ hard to implement, the tricky part will be just to make sure that it doesn't cause regressions haha.

**Comment by lnp5131** [comment] 2020-08-30 12:06
I would think that in terms of performance the main regression would only occur on initial load. Perhaps on mouseover it could preload the image before the shortcut is activated to combat that.

**Comment by qsniyg** [comment] 2020-08-30 15:24
I've finished implementing caching previous media (hopefully without bugs! haha), but not yet lookahead/preload. Since #151 already exists for more or less the same purpose, I'll close this one and use that issue to track preloading media :)

**Closed by qsniyg** 2020-08-30 15:24 UTC
Labels: enhancement, topic:userscript
