### ISSUE TITLE
canstockphoto.com

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#815] opened 2021-06-14 19:38 UTC
https://cdn.xxl.thumbs.canstockphoto.com/young-fit-woman-in-rome-italy-tying-shoelaces-gladiator-inspiring-trainings-young-fit-woman-in-picture_csp51141519.jpg
https://cdn.w600.comps.canstockphoto.com/young-fit-woman-in-rome-italy-tying-picture_csp51141519.jpg
https://www.canstockphoto.com/zoom/?height=382&width=598&id=51141519&_ts=1623703027801&scale=1.3377926421404682&left=0&top=127

Looks complicated.

**Comment by qsniyg** [comment] 2021-06-14 19:57
(Closing as a duplicate of #744)

I wasn't really sure how to go about it. As you can see, canstockphoto's zoom creates different images depending on the parameters, so it's a little difficult to get one that is "the best" image, in a sense. I'll have to play around with it some more to figure out how to support it.

By the way, do [feel free to email me](https://qsniyg.github.io/) if it's any easier than github for you. Just mentioning as I noticed you've gone through a few accounts, either way works fine for me :)

**Closed by qsniyg** 2021-06-14 19:57 UTC
Labels: duplicate, topic:rules
