### ISSUE TITLE
Tumblr broken

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#925] opened 2021-11-06 02:40 UTC
Likely due to some changes at `___INITIAL_STATE___`

userscript.ts#L33152 doesn't seem to be able to parse it anymore.

It looks to me the "remove regex" part 
```js
var json = match[1].replace(/(\"\s*:)\s*\/.*?\/\s*([,}])/g, "$1null$2");
```
no longer works, there are also `undefined` everythere needs to be dealt with before feeding into `JSON.parse`.

This is what I currently use in my own (Python) script for reference:
```py
json_string = m[1].replace('undefined', 'null')
json_string = re.sub(r'new RegExp\(.+\),', 'null,', json_string)
```

**Comment by schleeb** [comment] 2021-11-19 06:37
Dupe of #921

**Comment by qsniyg** [comment] 2021-12-12 03:28
Thanks! It should be fixed now

**Closed** 2021-12-12 03:27 UTC
Labels: bug, topic:rules
