### ISSUE TITLE
Support file format options

### ISSUE THREAD

**Issue by addisonxx** [qsniyg/maxurl#1298] opened 2024-03-10 02:29 UTC
Would it be possible to add an option for images from https://is1-ssl.mzstatic.com/ to be redirected to the jpg version instead of the png format?

**Comment by qsniyg** [comment] 2024-03-16 18:55
Thanks for the idea, I'll close this as a duplicate of https://github.com/qsniyg/maxurl/issues/761. One possible (although hacky) way for that option to work is to check if the only difference between the two URLs is the extension. Might be the easiest solution.

**Closed by qsniyg** 2024-03-16 18:55 UTC
Labels: topic:rules
