### ISSUE TITLE
Firefox add-on mouseover doesn't work on Tumblr photoset

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#201] opened 2020-01-26 02:11 UTC
Examples:

https://ikenaikoto.tumblr.com/post/190456259755/

When you mouse over any of the images, nothing happens. 

It works on single image post (ex: https://ikenaikoto.tumblr.com/post/190418711371/) or /image/ urls (ex: https://ikenaikoto.tumblr.com/image/190456259755/) , but not posts with photoset (multiple images).

But the userscript version works in both Firefox and Chrome.

I tried to supply my personal API key, no difference.

**Comment by qsniyg** [comment] 2020-01-26 04:21
It's because it's an iframe (#66), if you go to https://ikenaikoto.tumblr.com/post/190456259755/photoset_iframe/ikenaikoto/tumblr_q4nm82pvwd1s3zr8r/700/false, it'll work.

I'm honestly not entirely sure how to fix this, but I'll try and see if I can find a solution.

**Comment by fireattack** [comment] 2020-01-26 04:22
Interesting, any idea why it works for US but not add-on?

**Comment by qsniyg** [comment] 2020-01-26 04:26
@fireattack The reason why is because `all_frames` isn't set to `true` (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts), for some reason it didn't occur to me to do that. However, the iframe must still be selected before it works, which is a little annoying. I'll have to figure out a better solution.

**Comment by qsniyg** [comment] 2020-01-26 10:13
I'll close this as the issue is fixed in git master, though #66 is still relevant to this issue. I've made some progress regarding it, but a stable version will likely land in a future release, not the next one. However, the option ("Pop out of frames") will exist in the next release if you want to test it.

**Closed by qsniyg** 2020-01-26 10:13 UTC
Labels: bug, topic:userscript
