### ISSUE TITLE
Add support for some new image hostings

### ISSUE THREAD

**Issue by elvisef** [qsniyg/maxurl#601] opened 2021-01-06 15:52 UTC
Hello.

I have a small list of hostings that are not supported, and I am wondering if there is a chance to support them as well.

These are *(edited by developer)* :
~~[imgtown.net](imgtown.net)~~ *(can't be supported due to captcha)*
~~[imgmaze.com](imgmaze.com)/.pw~~ *(same as imgtown, can't be supported due to captcha)*
~~[imgview.net](imgview.net) aka [imgview.pw](imgview.pw)~~ *(same as imgtown, can't be supported due to captcha - though they use hcaptcha instead of recaptcha, good on them!)*
~~[imgoutlet.com](imgoutlet.com)/.pw~~ *(same as imgtown, can't be supported due to captcha)*
~~[imgdew.com](imgdew.com)/.pw~~ *(same as imgtown, can't be supported due to captcha)*
~~[imagedax.net](imagedax.net)~~ *(supported with https://github.com/qsniyg/maxurl/commit/8d77e0b3494841ec5f88a8ae4c72f40442458215)*
~~[imgbox.net](imgbox.net)~~ *(can't connect?)*
~~[imgbox.com](imgbox.com)~~ *(supported)*
~~[imgfrost.net](imgfrost.net)~~ *(redirects to fiyar.live, which is supported. explicit support added with https://github.com/qsniyg/maxurl/commit/02c8d9398d8e31523e724b6947909fe7ae723630)*

The list is based on which pages I meet while viewing Internet. So these ones above could not be retrieved.

PS.Is the "sites.txt'file updated sometimes ? You wrote that fore xample kropic was added but I don't see it there, is this important to update this file or I sould not check the support for certain pages there ?

**Comment by qsniyg** [comment] 2021-01-06 16:25
Thank you very much for this list!! I'll add support for them once I get a chance :) It's possible some of them can't be supported due to requiring captchas though.

sites.txt is usually updated when the script has a new release... I usually try to do them every week, but there are two really major changes (audio support - which already caused quite a few regressions I had to fix, and hls/dash downloading, which is in progress), so it might take a bit longer for this one, sorry!

**Comment by elvisef** [comment] 2021-01-06 17:06
No problem. Thanks !

Anyway, imgbox wre supported before You edited this line in my post, or not ?
Because I had an imgbox gallery and images were not resizing...

I'll recheck and let You know.

**Comment by qsniyg** [comment] 2021-01-07 07:21
Finished looking through them... as you can see, most of them force captchas unfortunately. Is imgbox.net still alive, or is it a typo?

As for imgbox.com, it's been supported for quite a long time... check my answer here: https://github.com/qsniyg/maxurl/issues/603

**Comment by elvisef** [comment] 2021-01-07 09:38
> Finished looking through them... as you can see, most of them force captchas unfortunately. Is imgbox.net still alive, or is it a typo?
> 
> As for imgbox.com, it's been supported for quite a long time... check my answer here: #603

For imgbox.net - it is not a typo, because I remember I had some links for this.
But something must have changed, because for now it shows Apache "welcome screen".
![2021-01-07_10-34](https://user-images.githubusercontent.com/25976749/103876492-ff828f00-50d3-11eb-84e5-6601f4f59c9b.png)

Btw, imgfrost was not working for me yesterday at all while using MaxURL FF addon that time, but now I will recheck it (You commited changes 3 hours ago).

**Comment by qsniyg** [comment] 2021-01-07 09:51
@elvisef Ah right, I forgot that you use the replace images feature. Yeah in that case, the new imgfrost addition should allow it to work :)

**Comment by elvisef** [comment] 2021-01-07 10:35
Alright, next one... : ]

imgfrost.net links I've found has direct (thumbnail) image links like these:
example1 - [https://www.fiyar.live/data_server_1/682/big/image_20180916_142838_1073copia.jpg](https://www.fiyar.live/data_server_1/682/big/image_20180916_142838_1073copia.jpg)
example2 - [https://www.fiyar.live/data_server_2/682/big/image_20180916_142838copia.jpg](https://www.fiyar.live/data_server_2/682/big/image_20180916_142838copia.jpg)
example3 - [https://www.fiyar.live/data_server_new/682/small/small_a_014(1).jpg](https://www.fiyar.live/data_server_new/682/small/small_a_014(1).jpg)

Example3 with pattern "data_server_new" does not work. Maybe something with the pattern ?

**Comment by qsniyg** [comment] 2021-01-07 10:41
Done :) https://github.com/qsniyg/maxurl/commit/b7f3675c76e03a8bc48db4591ff2aaafc2a5253b

**Comment by elvisef** [comment] 2021-01-07 11:06
> 
> 
> Done :) [b7f3675](https://github.com/qsniyg/maxurl/commit/b7f3675c76e03a8bc48db4591ff2aaafc2a5253b)

Works like a charm, thanks !

**Comment by qsniyg** [comment] 2021-01-07 11:25
Cool! I'll close the issue then :)

**Closed by qsniyg** 2021-01-07 11:25 UTC
Labels: topic:rules
