### ISSUE TITLE
Options doesn't appear on Edge

### ISSUE THREAD

**Issue by cbadoud** [qsniyg/maxurl#203] opened 2020-01-26 16:21 UTC
Even if script is installed and browser restarted, it's impossible to configure the options.

**Comment by qsniyg** [comment] 2020-01-26 16:22
@cbadoud Which version of Edge are you running? I haven't tested it yet as I'm using linux, but I'll fire up a virtual machine soon to test :)

**Comment by cbadoud** [comment] 2020-01-26 17:08
Hi,

I'm on Windows 10 v1909.

Thanks!

------ Message d'origine ------
De: "qsniyg" <notifications@github.com>
À: "qsniyg/maxurl" <maxurl@noreply.github.com>
Cc : "Christian" <cbadoud@bluewin.ch>; "Mention" 
<mention@noreply.github.com>
Envoyé : 26.01.2020 17:22:48
Objet : Re: [qsniyg/maxurl] Options doesn't appear on Edge (#203)

**Comment by qsniyg** [comment] 2020-01-26 17:49
@cbadoud Thanks, I'm currently updating to it. Are you running the new Edge ([the logo looks like this](https://s.yimg.com/os/creatr-uploaded-images/2019-11/c170cb90-fdba-11e9-a7ea-45d32c4412a4)) or the old one ([this logo](https://images.techhive.com/images/article/2015/04/microsoft-edge-100582336-orig.jpg))?

And are you using Tampermonkey as the userscript manager or something else?

I'm unable to reproduce this issue with the old Edge and Tampermonkey (it loads the options page without issue), but I'll try the new one once the updates have finished installing... :)

**Comment by qsniyg** [comment] 2020-01-26 19:17
The updates (finally) finished and I just tried the new Edge with Tampermonkey, but I'm still unable to replicate the issue... are you sure the userscript is installed properly in Tampermonkey?

**Comment by cbadoud** [comment] 2020-01-27 19:35
The old one. Maybe you can forget it because the new one will arrive 
soon.

------ Message d'origine ------
De: "qsniyg" <notifications@github.com>
À: "qsniyg/maxurl" <maxurl@noreply.github.com>
Cc : "Christian" <cbadoud@bluewin.ch>; "Mention" 
<mention@noreply.github.com>
Envoyé : 26.01.2020 20:17:03
Objet : Re: [qsniyg/maxurl] Options doesn't appear on Edge (#203)

**Comment by qsniyg** [comment] 2020-01-27 19:37
@cbadoud You can actually use the new one already, it's out of beta :) https://www.microsoft.com/en-us/edge

The old one also worked fine for me though... how did you install the script with it?

**Comment by cbadoud** [comment] 2020-01-27 19:38
With Tampermonkey.

------ Message d'origine ------
De: "qsniyg" <notifications@github.com>
À: "qsniyg/maxurl" <maxurl@noreply.github.com>
Cc : "Christian" <cbadoud@bluewin.ch>; "Mention" 
<mention@noreply.github.com>
Envoyé : 27.01.2020 20:37:23
Objet : Re: [qsniyg/maxurl] Options doesn't appear on Edge (#203)

**Comment by qsniyg** [comment] 2020-01-27 19:41
Does the tampermonkey icon have a "badge" (number) below it when you visit the options page? If so, can you click on it to make sure that it shows Image Max URL as one of the active userscripts on the page?

If it is indeed active, could you try pressing F12 to open the developers console, go to the "Console" tab, and check if there are any errors (if there are, can you send a screenshot)?

I'd like to try to fix this if possible (unless you plan to move to the new edge and you don't have the same issue there), but unfortunately I can't replicate it on my side

**Comment by cbadoud** [comment] 2020-01-27 19:48
Hi,
>Does the tampermonkey icon have a "badge" (number) below it when you 
>visit the options page? If so, can you click on it to make sure that it 
>shows Image Max URL as one of the active userscripts on the page?
>
There is no badge! I've just seen that extension is not active, even if 
this tab say the opposite:

>If it is indeed active, could you try pressing F12 to open the 
>developers console, go to the "Console" tab, and check if there are any 
>errors (if there are, can you send a screenshot)?
>
I think that there no relevant error:

>I'd like to try to fix this if possible (unless you plan to move to the 
>new edge and you don't have the same issue there), but unfortunately I 
>can't replicate it on my side
>
I don't want to try the new Edge since it's not officially launched.

Thanks for your reactivity!!!

**Comment by qsniyg** [comment] 2020-01-27 20:04
>I've just seen that extension is not active, even if this tab say the opposite:

By "that extension is not active", you're referring to Image Max URL in the options page, not Tampermonkey, correct?

>There is no badge!

I don't know if it's possible to do this, but could you try taking a screenshot of the popup when you click the Tampermonkey icon on the options page? Apparently pressing Windows+PrintScreen will do this (https://www.howtogeek.com/226280/how-to-take-screenshots-in-windows-10/).

**Comment by cbadoud** [comment] 2020-01-27 21:14
Sorry, I've found how to active Tampermonkey now, and everythink is OK 
now. Oups...

Anyway, I've found another situation where your extension doesn't work. 
On some websites, to get the biggest image, the idea is to replace 
"…-480x.jpg" or "…-1920x.jpg" with "…-fullsize.jpg" (see 
https://www.hegre.com/films/go-west-young-girl).

Thanks again.

------ Message d'origine ------
De: "qsniyg" <notifications@github.com>
À: "qsniyg/maxurl" <maxurl@noreply.github.com>
Cc : "Christian" <cbadoud@bluewin.ch>; "Mention" 
<mention@noreply.github.com>
Envoyé : 27.01.2020 21:04:54
Objet : Re: [qsniyg/maxurl] Options doesn't appear on Edge (#203)

**Comment by qsniyg** [comment] 2020-01-27 21:24
Thank you very much! Looks like they're using a new domain now, which is why the script didn't catch it :)

I'll close this issue as it looks like it's solved, but feel free to open a new issue if you encounter any more problems or site that aren't supported :)

**Closed by qsniyg** 2020-01-27 21:24 UTC
Labels: bug, topic:userscript

**Comment by cbadoud** [comment] 2020-01-27 21:42
Hi,
>Thank you very much! Looks like they're using a new domain now, which 
>is why the script didn't catch it :)
>
Who are you talking about? hegre.com?
>I'll close this issue as it looks like it's solved, but feel free to 
>open a new issue if you encounter any more problems or site that aren't 
>supported :)
>
I don't want to open an issue for this, but this website doesn't work 
too: https://www.theonemilano.com/brand_theone/cavalleri-c-2-2-2/  (your 
script is calling the button image).

Otherwise, your script is ABSOLUTELY FABULOUS!

**Comment by qsniyg** [comment] 2020-01-27 21:55
>Who are you talking about? hegre.com?

Yeah, the previous domain was cdn.public.hegre.com :)

Thanks for the link! I've fixed it, it'll be in the next update (probably will be released today).

And I'm really glad you like it! :)
